library(e1071)
library(caTools)
library(caret)
View(train)
df<- read.csv("/home/shaury/Downloads/nptel/Iris.csv")
set.seed(141)
sample = sample.split(df,SplitRatio=0.8)
train <- subset(df,sample==TRUE)
test <- subset(df,sample==FALSE)
cl<- naiveBayes( df$Species~.,data=df)
y_pred<- predict(cl,newdata=test)
table(y_pred,test$Species)
