```{r}
library(ISLR)
adult<- read.csv("adult_sal.csv",na.strings=c('?'));
head(adult)
```
```{r}
library(Amelia);
print(missmap(adult,main='Missing Map',col=c('yellow','black'),legend=FALSE));
```

```{r}
library(tidyverse)
pl<-ggplot(adult)+geom_bar(aes(income,fill=factor(race)));
print(pl);
```
```{r}
ggplot(adult)+geom_bar(aes(income,fill=factor(race)),position='dodge');
```

```{r}
ggplot(adult)+geom_bar(aes(income,fill=factor(education)))

```
```{r}
ggplot(adult)+geom_bar(aes(income,fill=factor(education)),position='dodge')
```

```{r}
ggplot(adult)+geom_bar(aes(income,fill=factor(marital)))
```

```{r}
ggplot(adult)+geom_bar(aes(income,fill=factor(marital)),position='dodge')
```

```{r}
ggplot(adult)+geom_bar(aes(income,fill=factor(type_employer)),position='dodge')
```

```{r}
ggplot(adult)+geom_bar(aes(income,fill=factor(hr_per_week)))
```

```{r}
ggplot(adult)+geom_bar(aes(income,fill=factor(occupation)))
```

```{r}
ggplot(adult)+geom_bar(aes(income,fill=factor(relationship)))
```

```{r}

```

