 df<-read.csv("/home/shaury/Downloads/nptel/winequality-red.csv")
 View(df)
 summary(df$quality)
  plot(df,col=c("red","blue","black","green","pink","yellow")[df$quality])
 temp<-c(1:1599)
 View(temp)
 df<-cbind(temp,df)
 View(df)
 library(tidyverse)
 ggplot(df)+geom_point(mapping=aes(df$temp,df$fixed.acidity,col=df$quality))
 ggplot(df)+geom_point(mapping=aes(df$temp,df$chlorides,col=df$quality))
 ggplot(df)+geom_point(mapping=aes(df$temp,df$alcohol,col=df$quality))
 ggplot(df)+geom_point(mapping=aes(df$temp,df$pH,col=df$quality))
 ggplot(df)+geom_point(mapping=aes(df$temp,df$sulphates,col=df$quality))
 library(caTools)
 set.seed(123)
 sample<-sample.split(df,SplitRatio=0.8)
 train<-subset(df,sample==TRUE)
 test<-subset(df,sample==FALSE)
 library(MASS)
 l1<-lda(train$quality~ train$chlorides+train$sulphates+train$pH+train$alcohol+train$fixed.acidity+train$volatile.acidity+train$citric.acid+train$residual.sugar+train$free.sulfur.dioxide+train$total.sulfur.dioxide+train$density)
 train=test
 pred<-predict(l1,train)
 table(pred$class,test$quality)
 mean(pred$class==test$quality)
 plot(l1)
 

